d3.select('svg')
    .append('rect')
    .attr('width',100)
    .attr('height',200)
    .attr('fill','red')
    .attr("class","c-rect")

d3.select('svg')
    .append('rect')
    .attr('width',300)
    .attr('height',600)
    .attr('fill','blue')
    .attr("class","c-rect")

d3.select('.c-rect')
    .attr('fill','black')
